server:
  compression:
    enabled: true
    mime-types: application/json,text/plain,text/html
    min-response-size: 1024
spring:
  data:
    redis:
      host: 47.111.22.183
      port: 6379
      password: 123456
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
# websocket配置
netty:
  websocket:
    # 端口
    port: 8000
#自定义编码器的序列化算法
serializer:
  algorithm: Json